#!/usr/bin/make -f
# DSP-only LV2 build of Can-Abyss Delay with the vendored DPF in ../../dpf
NAME = nhe-can-abyss
FILES_DSP = CanAbyssPlugin.cpp
include ../../dpf/Makefile.plugins.mk
TARGETS = lv2_dsp
all: $(TARGETS)
